plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty
relative_permalink: true

# Setup
title:            William Nash
tagline:          ''
description:      'Data Scientist / Engineer'
url:              https://williamnash.github.io/
baseurl:          /

paginate:         5

# Custom vars
version:          0.1.1

github:           
  repo:           https://github.com/williamnash/williamnash.github.io
